- brain/posenet.js
*We are still working on record + integrating this with record. #StepByStep
> wireframes global array now stores each pose/frame

- client/store/user.js
- server/api/index.js
- server/api/users.js
some user crud, nothing to important
> basic user api routes and redux edits

- client/components/AddTeamForm.js
- client/routes.js
* AddTeamForm is a semantic styled component
* It works
* There is an 'addform' on the router so I can look at it and test it - this can be removed
> AddTeamForm

- client/components/Navbar.js
- client/components/RecordPerformance.js
- client/components/RecordRoutine.js
- client/components/index.js
- client/routes.js
- package-lock.json
- package.json
- public/index-test.html
- public/index-test2.html
- public/index.html
- public/style.css
- public/videojs.record.js
* RecordPerformance component records video
* it does not break
* this is a huge deal
> Video react

- client/components/RecordRoutine.js
record routine is a class component now
it still works, pretty sure
> class is made

- client/components/Choreo.js
- client/components/RecordPractice.js
- client/components/RecordRoutine.js
- client/routes.js
- client/store/practice.js
- client/store/routine.js
- public/style.css
- server/api/practices.js
- server/api/routines.js
- server/db/models/index.js
* Record practice layout in place
* a few updates to routes
* am tired
> Record practice

- client/components/RecordPractice.js
- client/components/RecordRoutine.js
- client/store/routine.js
- package-lock.json
- package.json
- public/style.css
- script/seed.js
- server/api/routines.js
- server/db/models/CalibrationFrame.js
- server/db/models/VideoFrame.js
- utils/videoJsOptions.js
skellies show up on record practice except it's zoomed weird
> Wireframey

- client/components/RecordPractice.js
- frontUtils/draw.js
This only works because the video players are a specific constrained size
> Correctly scaled and refreshing skellies

- client/components/Choreo.js
- client/components/Navbar.js
- client/components/RecordPractice.js
- public/index.html
record practice shows the video you are practicing on
also I did some minor style fixes
> Choreo skellies

- client/components/Calibrator.js
- client/components/Choreo.js
- client/components/Dash_Sidebar.js
- client/components/Members.js
- client/components/Navbar.js
- client/components/RecordPractice.js
- client/components/Routines.js
- client/components/Team.js
- client/components/TeamList.js
- public/index.html
- public/style.css
- webpack.config.js
* Lots of making elements into SemanticUI
* Navbar record/practice links more useful for testing
* Styling
* updated dashboard menu to be consistent
* `<Choreo />` and `<RecordPractice />` components now have back buttons to team/routine, respectively
* removed files from public/index.html that were causing 404 errors
> Minorfixes

- client/components/AddMemberForm.js
- client/components/Calibrator.js
- client/components/PrevAttempts.js
- client/components/RecordRoutine.js
- client/components/UploadVideoForm.js
- client/store/routine.js
- script/seed.js
- server/api/calibration.js
- server/api/index.js
- server/db/models/Practice.js
- server/index.js
* camera takes photo and uploads to cloudinary
* skelly is generated and saved to calibration frame
* seed updated to accommodate the size of calibration string
* seed updated to generate wireframes (this will take a while)
> Calibration cam

- utils/formatting.js
> added unlabel pose function

- server/api/practices.js
- webpack.config.js
smol webpack update
also, small update to remove unused imports on an API route
> Fix heroku

- client/components/RecordPractice.js
- utils/geometry.js
- utils/scaling.js
- utils/scoring.js
we did it, kinda!
hip reversal complete!
> Scaling adventures

- client/components/RecordPractice.js
Through the power of IIFEs, everything has a reasonable scope.  Have not set up ability to do multiple attempts; intend to put that on a followup PR if this one's okay.
> Scopeissuesv2

- client/components/RecordPractice.js
- client/components/UploadVideoForm.js
- client/store/assignment.js
- client/store/practice.js
- client/store/routine.js
- public/style.css
- server/api/assignments.js
- server/api/practices.js
- server/api/routines.js
* Tweaks to `<RecordPractice />` upload functions to do all the things we need it to do
* Flip the skellies canvas so it matches the mirrored videos
* fiddled with the skellies' positions, as usual
> Practice functionality

- client/components/RecordRoutine.js
* record button countdown for routine
> record routine has countdown

- client/components/RecordPractice.js
recordpractice button + prevattempts up toward top again
> layout fix

- client/components/RecordPractice.js
- utils/videoJsOptions.js
* Plays both choreo and records on record
* otherwise generally doesn't break
* no delay though because that breaks it for some reason
> RecordRoutine Record button

- client/components/RecordPractice.js
- utils/videoJsOptions.js
> Optimization

- README.md
- backUtils/canvasify.js
- brain/test-posenet-methods.js
- client/components/AddMemberForm.js
- client/components/AddTeamForm.js
- client/components/RecordPractice.js
- client/components/RecordRoutine.js
- client/workers/videoNet.worker.js
- frontUtils/draw.js
- frontUtils/workarounds.js
- utils/formatting.js
- utils/geometry.js
- utils/posenet.js
- utils/scaling.js
- utils/scoring.js
- utils/videoJsOptions.js
- utils/videoProcessing.js
- videocapture/videorecord.js
I added a lot of comments to try to sort out what is really going on. When possible, they are in JSDocs format so we could generate documentation quite easily for it if we wanted :)
> Inline documentation

- client/components/AddMemberForm.js
- client/components/AddTeamForm.js
- client/components/AssignRoutine.js
- client/components/Assignments.js
- client/components/Auth-Form.js
- client/components/Calibrator.js
- client/components/Dash_Sidebar.js
- client/components/LoadingScreen.js
- client/components/Member.js
- client/components/MembersSidebar.js
- client/components/PrevAttempts.js
- client/components/RecordPractice.js
- client/components/RecordRoutine.js
- client/components/Routine.js
- client/components/Routines.js
- client/components/Team.js
- client/components/TeamList.js
- client/components/UploadVideoForm.js
- client/components/WFCanv.js
in addition to inline documentation, i've now added prop types for react components! Primarily for documentation - will throw errors in console if props received have types differing from what is listed.
> Prop types
